"""squads.json 생성기 — 48국 × 16명 실제 국가대표 풀스쿼드.

각 팀: 1 GK + 5 DEF + 5 MID + 5 FWD = 16명. 5명은 ★ 스타.
KOR만 한글, 나머지는 영문 (영자 표기).

실행: python soccer/generate_squads.py
출력: soccer/squads.json
"""
import json
from pathlib import Path


# (name, role, rating, is_star, pk_taker)
# 모든 선수가 실제 국가대표 — 2024~2025 호출 기준
SQUADS = {
    # ── Group A ───────────────────────────────────────────────
    'MEX': [
        ('Memo Ochoa', 'GK', 79, True, False),
        ('Cesar Montes', 'DEF', 78, False, False),
        ('Jesus Gallardo', 'DEF', 77, True, False),
        ('Johan Vasquez', 'DEF', 76, False, False),
        ('Jorge Sanchez', 'DEF', 74, False, False),
        ('Kevin Alvarez', 'DEF', 74, False, False),
        ('Edson Alvarez', 'MID', 81, True, True),
        ('Luis Romo', 'MID', 76, False, False),
        ('Erick Sanchez', 'MID', 75, False, False),
        ('Orbelin Pineda', 'MID', 75, False, False),
        ('Marcelo Flores', 'MID', 73, False, False),
        ('Hirving Lozano', 'FWD', 79, True, False),
        ('Raul Jimenez', 'FWD', 78, True, False),
        ('Santiago Gimenez', 'FWD', 80, False, False),
        ('Henry Martin', 'FWD', 76, False, False),
        ('Cesar Huerta', 'FWD', 74, False, False),
    ],
    'RSA': [
        ('Ronwen Williams', 'GK', 75, True, False),
        ('Mothobi Mvala', 'DEF', 72, True, False),
        ('Khuliso Mudau', 'DEF', 71, False, False),
        ('Aubrey Modiba', 'DEF', 71, False, False),
        ('Siyanda Xulu', 'DEF', 70, False, False),
        ('Grant Kekana', 'DEF', 70, False, False),
        ('Themba Zwane', 'MID', 73, True, False),
        ('Teboho Mokoena', 'MID', 73, False, True),
        ('Sphephelo Sithole', 'MID', 71, False, False),
        ('Patrick Maswanganyi', 'MID', 71, False, False),
        ('Mihlali Mayambela', 'MID', 70, False, False),
        ('Percy Tau', 'FWD', 75, True, False),
        ('Lyle Foster', 'FWD', 74, True, False),
        ('Iqraam Rayners', 'FWD', 72, False, False),
        ('Evidence Makgopa', 'FWD', 71, False, False),
        ('Thapelo Morena', 'FWD', 70, False, False),
    ],
    'KOR': [
        ('조현우', 'GK', 78, True, False),
        ('김민재', 'DEF', 86, True, False),
        ('김주성', 'DEF', 75, False, False),
        ('김영권', 'DEF', 74, False, False),
        ('이기제', 'DEF', 73, False, False),
        ('설영우', 'DEF', 72, False, False),
        ('이강인', 'MID', 88, True, True),
        ('황인범', 'MID', 78, False, False),
        ('이재성', 'MID', 76, False, False),
        ('정우영', 'MID', 74, False, False),
        ('백승호', 'MID', 72, False, False),
        ('손흥민', 'FWD', 88, True, False),
        ('황희찬', 'FWD', 80, True, False),
        ('조규성', 'FWD', 75, False, False),
        ('오현규', 'FWD', 83, False, False),
        ('양현준', 'DEF', 78, False, False),
    ],
    'CZE': [
        ('Jindrich Stanek', 'GK', 76, True, False),
        ('Vladimir Coufal', 'DEF', 75, True, False),
        ('Tomas Holes', 'DEF', 74, False, False),
        ('David Jurasek', 'DEF', 73, False, False),
        ('Robin Hranac', 'DEF', 72, False, False),
        ('Pavel Krejci', 'DEF', 71, False, False),
        ('Tomas Soucek', 'MID', 79, True, False),
        ('Lukas Provod', 'MID', 75, False, False),
        ('Pavel Sulc', 'MID', 74, False, False),
        ('Vaclav Cerny', 'MID', 74, False, False),
        ('Lukas Cerv', 'MID', 72, False, False),
        ('Patrik Schick', 'FWD', 80, True, True),
        ('Adam Hlozek', 'FWD', 76, True, False),
        ('Tomas Chory', 'FWD', 74, False, False),
        ('Mojmir Chytil', 'FWD', 73, False, False),
        ('Adam Karabec', 'FWD', 71, False, False),
    ],
    # ── Group B ───────────────────────────────────────────────
    'CAN': [
        ('Milan Borjan', 'GK', 74, True, False),
        ('Alistair Johnston', 'DEF', 76, False, False),
        ('Steven Vitoria', 'DEF', 73, False, False),
        ('Sam Adekugbe', 'DEF', 73, False, False),
        ('Richie Laryea', 'DEF', 72, False, False),
        ('Derek Cornelius', 'DEF', 72, False, False),
        ('Alphonso Davies', 'MID', 84, True, True),
        ('Stephen Eustaquio', 'MID', 77, True, False),
        ('Jonathan Osorio', 'MID', 74, False, False),
        ('Ismael Kone', 'MID', 73, False, False),
        ('Mathieu Choiniere', 'MID', 71, False, False),
        ('Jonathan David', 'FWD', 82, True, False),
        ('Cyle Larin', 'FWD', 76, True, False),
        ('Tajon Buchanan', 'FWD', 76, False, False),
        ('Jacob Shaffelburg', 'FWD', 73, False, False),
        ('Theo Bair', 'FWD', 72, False, False),
    ],
    'BIH': [
        ('Ibrahim Sehic', 'GK', 74, True, False),
        ('Sead Kolasinac', 'DEF', 77, True, False),
        ('Adrian Leon Barisic', 'DEF', 73, False, False),
        ('Dennis Hadzikadunic', 'DEF', 72, False, False),
        ('Amar Dedic', 'DEF', 73, False, False),
        ('Branimir Cipetic', 'DEF', 70, False, False),
        ('Miralem Pjanic', 'MID', 77, True, False),
        ('Rade Krunic', 'MID', 75, True, False),
        ('Edin Visca', 'MID', 73, False, False),
        ('Benjamin Tahirovic', 'MID', 73, False, False),
        ('Anel Ahmedhodzic', 'MID', 75, False, False),
        ('Edin Dzeko', 'FWD', 79, True, True),
        ('Ermedin Demirovic', 'FWD', 76, False, False),
        ('Dzenis Burnic', 'FWD', 72, False, False),
        ('Said Hamulic', 'FWD', 71, False, False),
        ('Smail Prevljak', 'FWD', 70, False, False),
    ],
    'QAT': [
        ('Saad Al-Sheeb', 'GK', 74, True, False),
        ('Bassam Al-Rawi', 'DEF', 73, True, False),
        ('Pedro Miguel', 'DEF', 72, False, False),
        ('Boualem Khoukhi', 'DEF', 72, False, False),
        ('Tarek Salman', 'DEF', 71, False, False),
        ('Ahmed Suhail', 'DEF', 70, False, False),
        ('Hassan Al-Haydos', 'MID', 75, True, False),
        ('Karim Boudiaf', 'MID', 73, False, False),
        ('Abdulaziz Hatem', 'MID', 72, False, False),
        ('Mohammed Waad', 'MID', 71, False, False),
        ('Ahmed Fathi', 'MID', 70, False, False),
        ('Akram Afif', 'FWD', 77, True, True),
        ('Almoez Ali', 'FWD', 75, True, False),
        ('Hassan Al-Shahrani', 'FWD', 72, False, False),
        ('Mohamed Muntari', 'FWD', 71, False, False),
        ('Yusuf Abdurisag', 'FWD', 70, False, False),
    ],
    'SUI': [
        ('Yann Sommer', 'GK', 81, True, False),
        ('Manuel Akanji', 'DEF', 81, True, False),
        ('Ricardo Rodriguez', 'DEF', 76, False, False),
        ('Nico Elvedi', 'DEF', 76, False, False),
        ('Fabian Schar', 'DEF', 77, False, False),
        ('Silvan Widmer', 'DEF', 73, False, False),
        ('Granit Xhaka', 'MID', 82, True, True),
        ('Remo Freuler', 'MID', 77, False, False),
        ('Xherdan Shaqiri', 'MID', 77, True, False),
        ('Denis Zakaria', 'MID', 76, False, False),
        ('Michel Aebischer', 'MID', 73, False, False),
        ('Breel Embolo', 'FWD', 77, True, False),
        ('Zeki Amdouni', 'FWD', 76, False, False),
        ('Ruben Vargas', 'FWD', 75, False, False),
        ('Dan Ndoye', 'FWD', 74, False, False),
        ('Renato Steffen', 'FWD', 72, False, False),
    ],
    # ── Group C ───────────────────────────────────────────────
    'BRA': [
        ('Alisson', 'GK', 89, True, False),
        ('Marquinhos', 'DEF', 86, True, False),
        ('Gabriel Magalhaes', 'DEF', 84, False, False),
        ('Eder Militao', 'DEF', 84, False, False),
        ('Danilo', 'DEF', 81, False, False),
        ('Wendell', 'DEF', 76, False, False),
        ('Casemiro', 'MID', 85, True, False),
        ('Bruno Guimaraes', 'MID', 84, False, False),
        ('Lucas Paqueta', 'MID', 82, False, False),
        ('Andre', 'MID', 78, False, False),
        ('Joao Gomes', 'MID', 77, False, False),
        ('Vinicius Jr', 'FWD', 90, True, True),
        ('Rodrygo', 'FWD', 87, True, False),
        ('Raphinha', 'FWD', 84, False, False),
        ('Endrick', 'FWD', 80, False, False),
        ('Richarlison', 'FWD', 80, False, False),
    ],
    'MAR': [
        ('Yassine Bounou', 'GK', 82, True, False),
        ('Achraf Hakimi', 'DEF', 85, True, True),
        ('Romain Saiss', 'DEF', 78, False, False),
        ('Nayef Aguerd', 'DEF', 78, False, False),
        ('Noussair Mazraoui', 'DEF', 79, False, False),
        ('Adam Masina', 'DEF', 75, False, False),
        ('Sofyan Amrabat', 'MID', 80, True, False),
        ('Hakim Ziyech', 'MID', 82, True, False),
        ('Azzedine Ounahi', 'MID', 79, False, False),
        ('Bilal El Khannouss', 'MID', 76, False, False),
        ('Selim Amallah', 'MID', 75, False, False),
        ('Youssef En-Nesyri', 'FWD', 80, True, False),
        ('Ayoub El Kaabi', 'FWD', 78, False, False),
        ('Soufiane Rahimi', 'FWD', 75, False, False),
        ('Eliesse Ben Seghir', 'FWD', 74, False, False),
        ('Abdessamad Ezzalzouli', 'FWD', 74, False, False),
    ],
    'HAI': [
        ('Johny Placide', 'GK', 71, True, False),
        ('Andy Najar', 'DEF', 71, True, False),
        ('Carlens Arcus', 'DEF', 70, False, False),
        ('Ricardo Adé', 'DEF', 70, False, False),
        ('Garven Metusala', 'DEF', 69, False, False),
        ('Wilde-Donald Guerrier', 'DEF', 69, False, False),
        ('Steeven Saba', 'MID', 70, True, False),
        ('Soni Mustivar', 'MID', 70, False, False),
        ('Derrick Etienne', 'MID', 71, False, False),
        ('Leverton Pierre', 'MID', 68, False, False),
        ('Carlo Sainvil', 'MID', 67, False, False),
        ('Frantzdy Pierrot', 'FWD', 72, True, True),
        ('Duckens Nazon', 'FWD', 70, True, False),
        ('Mondy Prunier', 'FWD', 68, False, False),
        ('Kervens Belfort', 'FWD', 68, False, False),
        ('Roberto Lopes', 'FWD', 67, False, False),
    ],
    'SCO': [
        ('Angus Gunn', 'GK', 76, True, False),
        ('Andy Robertson', 'DEF', 84, True, True),
        ('Kieran Tierney', 'DEF', 78, True, False),
        ('Jack Hendry', 'DEF', 75, False, False),
        ('Ryan Porteous', 'DEF', 73, False, False),
        ('Grant Hanley', 'DEF', 73, False, False),
        ('Scott McTominay', 'MID', 80, True, False),
        ('John McGinn', 'MID', 79, True, False),
        ('Callum McGregor', 'MID', 77, False, False),
        ('Billy Gilmour', 'MID', 75, False, False),
        ('Stuart Armstrong', 'MID', 74, False, False),
        ('Che Adams', 'FWD', 76, False, False),
        ('Lyndon Dykes', 'FWD', 75, False, False),
        ('Lawrence Shankland', 'FWD', 74, False, False),
        ('Tommy Conway', 'FWD', 72, False, False),
        ('Ben Doak', 'FWD', 73, False, False),
    ],
    # ── Group D ───────────────────────────────────────────────
    'USA': [
        ('Matt Turner', 'GK', 77, True, False),
        ('Sergino Dest', 'DEF', 77, True, False),
        ('Tim Ream', 'DEF', 75, False, False),
        ('Chris Richards', 'DEF', 76, False, False),
        ('Antonee Robinson', 'DEF', 78, False, False),
        ('Joe Scally', 'DEF', 73, False, False),
        ('Tyler Adams', 'MID', 79, True, False),
        ('Weston McKennie', 'MID', 77, True, False),
        ('Yunus Musah', 'MID', 78, False, False),
        ('Gio Reyna', 'MID', 76, False, False),
        ('Luca de la Torre', 'MID', 73, False, False),
        ('Christian Pulisic', 'FWD', 82, True, True),
        ('Folarin Balogun', 'FWD', 78, False, False),
        ('Ricardo Pepi', 'FWD', 76, False, False),
        ('Tim Weah', 'FWD', 75, False, False),
        ('Brenden Aaronson', 'FWD', 74, False, False),
    ],
    'PAR': [
        ('Antony Silva', 'GK', 74, True, False),
        ('Gustavo Gomez', 'DEF', 77, True, False),
        ('Junior Alonso', 'DEF', 75, False, False),
        ('Omar Alderete', 'DEF', 74, False, False),
        ('Robert Rojas', 'DEF', 72, False, False),
        ('Juan Caceres', 'DEF', 72, False, False),
        ('Miguel Almiron', 'MID', 77, True, False),
        ('Damian Bobadilla', 'MID', 74, True, False),
        ('Andres Cubas', 'MID', 73, False, False),
        ('Mathias Villasanti', 'MID', 73, False, False),
        ('Diego Gomez', 'MID', 72, False, False),
        ('Antonio Sanabria', 'FWD', 77, True, True),
        ('Julio Enciso', 'FWD', 75, False, False),
        ('Adam Bareiro', 'FWD', 73, False, False),
        ('Ramon Sosa', 'FWD', 73, False, False),
        ('Alex Arce', 'FWD', 72, False, False),
    ],
    'AUS': [
        ('Mat Ryan', 'GK', 77, True, False),
        ('Harry Souttar', 'DEF', 76, False, False),
        ('Kye Rowles', 'DEF', 75, False, False),
        ('Aziz Behich', 'DEF', 74, True, False),
        ('Milos Degenek', 'DEF', 73, False, False),
        ('Cameron Burgess', 'DEF', 72, False, False),
        ('Aaron Mooy', 'MID', 76, True, True),
        ('Ajdin Hrustic', 'MID', 75, False, False),
        ('Riley McGree', 'MID', 74, False, False),
        ('Connor Metcalfe', 'MID', 73, False, False),
        ('Keanu Baccus', 'MID', 72, False, False),
        ('Mathew Leckie', 'FWD', 75, True, False),
        ('Mitchell Duke', 'FWD', 73, True, False),
        ('Kusini Yengi', 'FWD', 73, False, False),
        ('Awer Mabil', 'FWD', 72, False, False),
        ('Jamie Maclaren', 'FWD', 72, False, False),
    ],
    'TUR': [
        ('Ugurcan Cakir', 'GK', 79, True, False),
        ('Merih Demiral', 'DEF', 78, False, False),
        ('Caglar Soyuncu', 'DEF', 76, False, False),
        ('Mert Muldur', 'DEF', 74, False, False),
        ('Ferdi Kadioglu', 'DEF', 76, False, False),
        ('Samet Akaydin', 'DEF', 73, False, False),
        ('Hakan Calhanoglu', 'MID', 84, True, True),
        ('Arda Guler', 'MID', 80, True, False),
        ('Cengiz Under', 'MID', 79, True, False),
        ('Ismail Yuksek', 'MID', 74, False, False),
        ('Salih Ozcan', 'MID', 75, False, False),
        ('Kenan Yildiz', 'FWD', 78, True, False),
        ('Baris Alper Yilmaz', 'FWD', 76, False, False),
        ('Yusuf Yazici', 'FWD', 74, False, False),
        ('Semih Kilicsoy', 'FWD', 73, False, False),
        ('Bertug Yildirim', 'FWD', 72, False, False),
    ],
    # ── Group E ───────────────────────────────────────────────
    'GER': [
        ('Manuel Neuer', 'GK', 87, True, False),
        ('Joshua Kimmich', 'MID', 86, True, False),  # Kimmich often plays RB; but let's place him at MID
        ('Antonio Rudiger', 'DEF', 85, False, False),
        ('Jonathan Tah', 'DEF', 82, False, False),
        ('David Raum', 'DEF', 78, False, False),
        ('Maximilian Mittelstadt', 'DEF', 76, False, False),
        ('Nico Schlotterbeck', 'DEF', 80, False, False),
        ('Jamal Musiala', 'MID', 87, True, True),
        ('Florian Wirtz', 'MID', 86, True, False),
        ('Pascal Gross', 'MID', 76, False, False),
        ('Robert Andrich', 'MID', 76, False, False),
        ('Kai Havertz', 'FWD', 84, True, False),
        ('Niclas Fullkrug', 'FWD', 79, False, False),
        ('Leroy Sane', 'FWD', 84, False, False),
        ('Serge Gnabry', 'FWD', 82, False, False),
        ('Deniz Undav', 'FWD', 76, False, False),
    ],
    'CUW': [
        ('Eloy Room', 'GK', 73, True, False),
        ('Cuco Martina', 'DEF', 72, True, False),
        ('Jurien Gaari', 'DEF', 70, False, False),
        ('Roshon van Eijma', 'DEF', 69, False, False),
        ('Sherel Floranus', 'DEF', 70, False, False),
        ('Dilyan Soto', 'DEF', 68, False, False),
        ('Leandro Bacuna', 'MID', 73, True, True),
        ('Tahith Chong', 'MID', 72, True, False),
        ('Juninho Bacuna', 'MID', 71, False, False),
        ('Charlison Benschop', 'MID', 69, False, False),
        ('Gevaro Nepomuceno', 'MID', 69, False, False),
        ('Mizael Caroli', 'FWD', 70, True, False),
        ('Jurgen Locadia', 'FWD', 72, False, False),
        ('Vurnon Anita', 'FWD', 69, False, False),
        ('Rangelo Janga', 'FWD', 69, False, False),
        ('Cuco Martina Jr', 'FWD', 67, False, False),
    ],
    'CIV': [
        ('Yahia Fofana', 'GK', 74, False, False),
        ('Eric Bailly', 'DEF', 77, True, False),
        ('Wilfried Singo', 'DEF', 78, False, False),
        ('Evan Ndicka', 'DEF', 76, False, False),
        ('Ghislain Konan', 'DEF', 74, False, False),
        ('Serge Aurier', 'DEF', 75, False, False),
        ('Franck Kessie', 'MID', 82, True, False),
        ('Wilfried Zaha', 'MID', 80, True, False),
        ('Ibrahim Sangare', 'MID', 79, False, False),
        ('Seko Fofana', 'MID', 78, False, False),
        ('Jean Michael Seri', 'MID', 75, False, False),
        ('Sebastien Haller', 'FWD', 80, True, True),
        ('Yann Diomande', 'FWD', 75, True, False),
        ('Nicolas Pepe', 'FWD', 78, False, False),
        ('Simon Adingra', 'FWD', 76, False, False),
        ('Jonathan Bamba', 'FWD', 74, False, False),
    ],
    'ECU': [
        ('Hernan Galindez', 'GK', 75, True, False),
        ('Pervis Estupinan', 'DEF', 79, True, False),
        ('Piero Hincapie', 'DEF', 79, True, False),
        ('Felix Torres', 'DEF', 75, False, False),
        ('Angelo Preciado', 'DEF', 74, False, False),
        ('William Pacho', 'DEF', 78, False, False),
        ('Moises Caicedo', 'MID', 82, True, True),
        ('Jhegson Mendez', 'MID', 75, False, False),
        ('Alan Franco', 'MID', 74, False, False),
        ('Kendry Paez', 'MID', 76, False, False),
        ('Jeremy Sarmiento', 'MID', 73, False, False),
        ('Enner Valencia', 'FWD', 80, True, False),
        ('Kevin Rodriguez', 'FWD', 73, False, False),
        ('Leonardo Campana', 'FWD', 73, False, False),
        ('Gonzalo Plata', 'FWD', 76, False, False),
        ('John Yeboah', 'FWD', 72, False, False),
    ],
    # ── Group F ───────────────────────────────────────────────
    'NED': [
        ('Justin Bijlow', 'GK', 77, True, False),
        ('Virgil van Dijk', 'DEF', 89, True, True),
        ('Matthijs de Ligt', 'DEF', 84, False, False),
        ('Nathan Ake', 'DEF', 82, False, False),
        ('Denzel Dumfries', 'DEF', 80, False, False),
        ('Lutsharel Geertruida', 'DEF', 76, False, False),
        ('Frenkie de Jong', 'MID', 87, True, False),
        ('Tijjani Reijnders', 'MID', 81, False, False),
        ('Xavi Simons', 'MID', 82, False, False),
        ('Jerdy Schouten', 'MID', 76, False, False),
        ('Joey Veerman', 'MID', 74, False, False),
        ('Memphis Depay', 'FWD', 84, True, False),
        ('Cody Gakpo', 'FWD', 84, True, False),
        ('Wout Weghorst', 'FWD', 78, False, False),
        ('Brian Brobbey', 'FWD', 76, False, False),
        ('Donyell Malen', 'FWD', 78, False, False),
    ],
    'JPN': [
        ('Zion Suzuki', 'GK', 76, False, False),
        ('Ko Itakura', 'DEF', 78, False, False),
        ('Takehiro Tomiyasu', 'DEF', 79, False, False),
        ('Hiroki Ito', 'DEF', 76, False, False),
        ('Yukinari Sugawara', 'DEF', 74, False, False),
        ('Hiroki Sakai', 'DEF', 73, False, False),
        ('Wataru Endo', 'MID', 80, True, False),
        ('Takefusa Kubo', 'MID', 82, True, False),
        ('Daichi Kamada', 'MID', 80, True, False),
        ('Hidemasa Morita', 'MID', 76, False, False),
        ('Junya Ito', 'MID', 76, False, False),
        ('Kaoru Mitoma', 'FWD', 83, True, True),
        ('Daizen Maeda', 'FWD', 77, True, False),
        ('Ayase Ueda', 'FWD', 75, False, False),
        ('Mao Hosoya', 'FWD', 73, False, False),
        ('Takuma Asano', 'FWD', 73, False, False),
    ],
    'SWE': [
        ('Robin Olsen', 'GK', 77, True, False),
        ('Victor Lindelof', 'DEF', 79, True, False),
        ('Isak Hien', 'DEF', 76, False, False),
        ('Gabriel Gudmundsson', 'DEF', 73, False, False),
        ('Emil Krafth', 'DEF', 73, False, False),
        ('Daniel Sundgren', 'DEF', 71, False, False),
        ('Jens Cajuste', 'MID', 75, False, False),
        ('Mattias Svanberg', 'MID', 74, False, False),
        ('Albin Ekdal', 'MID', 73, False, False),
        ('Kristoffer Olsson', 'MID', 73, False, False),
        ('Daniel Svensson', 'MID', 72, False, False),
        ('Alexander Isak', 'FWD', 84, True, True),
        ('Viktor Gyokeres', 'FWD', 82, True, False),
        ('Dejan Kulusevski', 'FWD', 80, True, False),
        ('Anthony Elanga', 'FWD', 76, False, False),
        ('Emil Forsberg', 'FWD', 76, False, False),
    ],
    'TUN': [
        ('Aymen Dahmen', 'GK', 74, True, False),
        ('Dylan Bronn', 'DEF', 75, True, False),
        ('Yan Valery', 'DEF', 73, False, False),
        ('Mortadha Ben Ouanes', 'DEF', 72, False, False),
        ('Ali Maaloul', 'DEF', 72, False, False),
        ('Montassar Talbi', 'DEF', 72, False, False),
        ('Aissa Laidouni', 'MID', 75, True, False),
        ('Hannibal Mejbri', 'MID', 76, True, True),
        ('Ferjani Sassi', 'MID', 73, False, False),
        ('Ellyes Skhiri', 'MID', 76, False, False),
        ('Mohamed Drager', 'MID', 71, False, False),
        ('Wahbi Khazri', 'FWD', 76, True, False),
        ('Youssef Msakni', 'FWD', 75, False, False),
        ('Issam Jebali', 'FWD', 73, False, False),
        ('Naim Sliti', 'FWD', 73, False, False),
        ('Seifeddine Jaziri', 'FWD', 72, False, False),
    ],
    # ── Group G ───────────────────────────────────────────────
    'BEL': [
        ('Thibaut Courtois', 'GK', 89, True, False),
        ('Wout Faes', 'DEF', 77, True, False),
        ('Arthur Theate', 'DEF', 76, False, False),
        ('Zeno Debast', 'DEF', 75, False, False),
        ('Timothy Castagne', 'DEF', 76, False, False),
        ('Maxim de Cuyper', 'DEF', 74, False, False),
        ('Kevin De Bruyne', 'MID', 89, True, True),
        ('Youri Tielemans', 'MID', 80, False, False),
        ('Amadou Onana', 'MID', 80, False, False),
        ('Leandro Trossard', 'MID', 80, False, False),
        ('Hans Vanaken', 'MID', 75, False, False),
        ('Romelu Lukaku', 'FWD', 86, True, False),
        ('Jeremy Doku', 'FWD', 82, True, False),
        ('Dodi Lukebakio', 'FWD', 76, False, False),
        ('Charles De Ketelaere', 'FWD', 76, False, False),
        ('Loïs Openda', 'FWD', 81, False, False),
    ],
    'EGY': [
        ('Mohamed Abou Gabal', 'GK', 75, True, False),
        ('Hamdy Fathy', 'DEF', 74, True, False),
        ('Ahmed Hegazi', 'DEF', 74, False, False),
        ('Omar Kamal', 'DEF', 72, False, False),
        ('Ahmed Fatouh', 'DEF', 71, False, False),
        ('Ahmed Sayed', 'DEF', 70, False, False),
        ('Mohamed Elneny', 'MID', 77, True, False),
        ('Emam Ashour', 'MID', 75, False, False),
        ('Tarek Hamed', 'MID', 73, False, False),
        ('Ramadan Sobhi', 'MID', 74, False, False),
        ('Mahmoud Trezeguet', 'MID', 75, False, False),
        ('Mohamed Salah', 'FWD', 89, True, True),
        ('Mostafa Mohamed', 'FWD', 76, True, False),
        ('Omar Marmoush', 'FWD', 78, False, False),
        ('Ahmed Sayed Zizo', 'FWD', 73, False, False),
        ('Marwan Mohsen', 'FWD', 71, False, False),
    ],
    'IRN': [
        ('Ali Beiranvand', 'GK', 78, True, False),
        ('Ehsan Hajsafi', 'DEF', 74, True, False),
        ('Morteza Pouraliganji', 'DEF', 73, False, False),
        ('Sadegh Moharrami', 'DEF', 73, False, False),
        ('Milad Mohammadi', 'DEF', 72, False, False),
        ('Hossein Kanaanizadegan', 'DEF', 72, False, False),
        ('Ahmad Nourollahi', 'MID', 76, True, False),
        ('Saeid Ezatolahi', 'MID', 74, False, False),
        ('Saman Ghoddos', 'MID', 74, False, False),
        ('Vahid Amiri', 'MID', 72, False, False),
        ('Alireza Jahanbakhsh', 'MID', 75, False, False),
        ('Mehdi Taremi', 'FWD', 80, True, True),
        ('Sardar Azmoun', 'FWD', 79, True, False),
        ('Karim Ansarifard', 'FWD', 73, False, False),
        ('Mehdi Ghayedi', 'FWD', 73, False, False),
        ('Allahyar Sayyadmanesh', 'FWD', 72, False, False),
    ],
    'NZL': [
        ('Max Crocombe', 'GK', 71, True, False),
        ('Tim Payne', 'DEF', 72, True, False),
        ('Liberato Cacace', 'DEF', 73, True, False),
        ('Michael Boxall', 'DEF', 71, False, False),
        ('Tyler Bindon', 'DEF', 70, False, False),
        ('Nando Pijnaker', 'DEF', 69, False, False),
        ('Sarpreet Singh', 'MID', 73, True, False),
        ('Joe Bell', 'MID', 71, False, False),
        ('Marko Stamenic', 'MID', 71, False, False),
        ('Matthew Garbett', 'MID', 70, False, False),
        ('Clayton Lewis', 'MID', 68, False, False),
        ('Chris Wood', 'FWD', 76, True, True),
        ('Kosta Barbarouses', 'FWD', 71, False, False),
        ('Ben Waine', 'FWD', 71, False, False),
        ('Logan Rogerson', 'FWD', 69, False, False),
        ('Storm Roux', 'FWD', 68, False, False),
    ],
    # ── Group H ───────────────────────────────────────────────
    'ESP': [
        ('Unai Simon', 'GK', 82, True, False),
        ('Daniel Carvajal', 'DEF', 82, False, False),
        ('Aymeric Laporte', 'DEF', 81, False, False),
        ('Robin Le Normand', 'DEF', 80, False, False),
        ('Marc Cucurella', 'DEF', 78, False, False),
        ('Pau Cubarsi', 'DEF', 80, False, False),
        ('Rodri', 'MID', 89, True, False),
        ('Pedri', 'MID', 86, True, False),
        ('Fabian Ruiz', 'MID', 82, False, False),
        ('Martin Zubimendi', 'MID', 80, False, False),
        ('Mikel Merino', 'MID', 79, False, False),
        ('Lamine Yamal', 'FWD', 87, True, True),
        ('Nico Williams', 'FWD', 84, True, False),
        ('Alvaro Morata', 'FWD', 81, False, False),
        ('Mikel Oyarzabal', 'FWD', 80, False, False),
        ('Ferran Torres', 'FWD', 80, False, False),
    ],
    'CPV': [
        ('Vozinha', 'GK', 73, True, False),
        ('Logan Costa', 'DEF', 74, True, False),
        ('Stopira', 'DEF', 73, True, False),
        ('Diney', 'DEF', 70, False, False),
        ('Kenny Rocha', 'DEF', 70, False, False),
        ('Nilton Varela', 'DEF', 69, False, False),
        ('Nuno Borges', 'MID', 72, False, False),
        ('Jamiro Monteiro', 'MID', 73, False, False),
        ('Yannick Semedo', 'MID', 71, False, False),
        ('Patrick Andrade', 'MID', 70, False, False),
        ('Laros Duarte', 'MID', 71, False, False),
        ('Ryan Mendes', 'FWD', 76, True, True),
        ('Bebe', 'FWD', 72, True, False),
        ('Garry Rodrigues', 'FWD', 72, False, False),
        ('Gilson Tavares', 'FWD', 70, False, False),
        ('Willy Semedo', 'FWD', 70, False, False),
    ],
    'KSA': [
        ('Mohammed Al-Owais', 'GK', 75, True, False),
        ('Yasser Al-Shahrani', 'DEF', 75, True, False),
        ('Ali Al-Bulaihi', 'DEF', 74, False, False),
        ('Hassan Tambakti', 'DEF', 73, False, False),
        ('Sultan Al-Ghannam', 'DEF', 73, False, False),
        ('Saud Abdulhamid', 'DEF', 73, False, False),
        ('Salman Al-Faraj', 'MID', 75, True, False),
        ('Mohamed Kanno', 'MID', 74, False, False),
        ('Nasser Al-Dawsari', 'MID', 73, False, False),
        ('Abdullah Otayf', 'MID', 73, False, False),
        ('Hattan Bahebri', 'MID', 73, False, False),
        ('Salem Al-Dawsari', 'FWD', 78, True, True),
        ('Saleh Al-Shehri', 'FWD', 76, True, False),
        ('Abdullah Al-Hamdan', 'FWD', 73, False, False),
        ('Firas Al-Buraikan', 'FWD', 73, False, False),
        ('Mohamed Al-Saiari', 'FWD', 71, False, False),
    ],
    'URU': [
        ('Sergio Rochet', 'GK', 76, True, False),
        ('Ronald Araujo', 'DEF', 84, True, False),
        ('Jose Maria Gimenez', 'DEF', 82, False, False),
        ('Sebastian Caceres', 'DEF', 76, False, False),
        ('Mathias Olivera', 'DEF', 76, False, False),
        ('Nahitan Nandez', 'DEF', 76, False, False),
        ('Federico Valverde', 'MID', 86, True, True),
        ('Manuel Ugarte', 'MID', 80, False, False),
        ('Rodrigo Bentancur', 'MID', 80, False, False),
        ('Maxi Araujo', 'MID', 77, True, False),
        ('Nicolas de la Cruz', 'MID', 78, False, False),
        ('Darwin Nunez', 'FWD', 82, True, False),
        ('Maximiliano Araujo', 'FWD', 76, False, False),
        ('Facundo Pellistri', 'FWD', 76, False, False),
        ('Brian Rodriguez', 'FWD', 75, False, False),
        ('Luis Suarez', 'FWD', 80, False, False),
    ],
    # ── Group I ───────────────────────────────────────────────
    'FRA': [
        ('Mike Maignan', 'GK', 85, True, False),
        ('William Saliba', 'DEF', 85, True, False),
        ('Dayot Upamecano', 'DEF', 83, False, False),
        ('Theo Hernandez', 'DEF', 82, False, False),
        ('Jules Kounde', 'DEF', 82, False, False),
        ('Ferland Mendy', 'DEF', 78, False, False),
        ('Aurelien Tchouameni', 'MID', 84, True, False),
        ('Antoine Griezmann', 'MID', 86, True, False),
        ('Eduardo Camavinga', 'MID', 82, False, False),
        ('N\'Golo Kante', 'MID', 80, False, False),
        ('Adrien Rabiot', 'MID', 80, False, False),
        ('Kylian Mbappe', 'FWD', 91, True, True),
        ('Ousmane Dembele', 'FWD', 84, False, False),
        ('Marcus Thuram', 'FWD', 82, False, False),
        ('Bradley Barcola', 'FWD', 80, False, False),
        ('Randal Kolo Muani', 'FWD', 79, False, False),
    ],
    'SEN': [
        ('Edouard Mendy', 'GK', 80, True, False),
        ('Kalidou Koulibaly', 'DEF', 82, True, False),
        ('Abdou Diallo', 'DEF', 76, False, False),
        ('Youssouf Sabaly', 'DEF', 75, False, False),
        ('Fode Ballo-Toure', 'DEF', 73, False, False),
        ('Pape Abou Cisse', 'DEF', 73, False, False),
        ('Idrissa Gana Gueye', 'MID', 79, True, False),
        ('Pape Matar Sarr', 'MID', 78, False, False),
        ('Krepin Diatta', 'MID', 75, False, False),
        ('Pathe Ciss', 'MID', 73, False, False),
        ('Lamine Camara', 'MID', 76, False, False),
        ('Sadio Mane', 'FWD', 84, True, True),
        ('Ismaila Sarr', 'FWD', 79, True, False),
        ('Boulaye Dia', 'FWD', 78, False, False),
        ('Habib Diallo', 'FWD', 76, False, False),
        ('Nicolas Jackson', 'FWD', 78, False, False),
    ],
    'IRQ': [
        ('Hussein Ali', 'GK', 73, True, False),
        ('Ali Adnan', 'DEF', 74, True, False),
        ('Rebin Sulaka', 'DEF', 71, False, False),
        ('Mustafa Nadhim', 'DEF', 71, False, False),
        ('Manaf Younis', 'DEF', 70, False, False),
        ('Ahmed Yahya', 'DEF', 70, False, False),
        ('Bashar Resan', 'MID', 72, True, False),
        ('Amir Al-Ammari', 'MID', 72, False, False),
        ('Ibrahim Bayesh', 'MID', 71, False, False),
        ('Hassan Ali', 'MID', 70, False, False),
        ('Sherko Karim', 'MID', 70, False, False),
        ('Aymen Hussein', 'FWD', 75, True, True),
        ('Mohanad Ali', 'FWD', 73, True, False),
        ('Ali Al-Hamadi', 'FWD', 72, False, False),
        ('Zidane Iqbal', 'FWD', 72, False, False),
        ('Mohammed Qasim', 'FWD', 70, False, False),
    ],
    'NOR': [
        ('Orjan Nyland', 'GK', 75, True, False),
        ('Kristoffer Ajer', 'DEF', 76, False, False),
        ('Stefan Strandberg', 'DEF', 73, False, False),
        ('Leo Ostigard', 'DEF', 75, False, False),
        ('Birger Meling', 'DEF', 73, False, False),
        ('Julian Ryerson', 'DEF', 75, False, False),
        ('Martin Odegaard', 'MID', 86, True, False),
        ('Sander Berge', 'MID', 77, True, False),
        ('Patrick Berg', 'MID', 73, False, False),
        ('Fredrik Aursnes', 'MID', 75, False, False),
        ('Mathias Normann', 'MID', 73, False, False),
        ('Erling Haaland', 'FWD', 91, True, True),
        ('Alexander Sorloth', 'FWD', 80, True, False),
        ('Antonio Nusa', 'FWD', 76, False, False),
        ('Mohamed Elyounoussi', 'FWD', 76, False, False),
        ('Jorgen Strand Larsen', 'FWD', 75, False, False),
    ],
    # ── Group J ───────────────────────────────────────────────
    'ARG': [
        ('Emiliano Martinez', 'GK', 87, True, False),
        ('Cristian Romero', 'DEF', 84, True, False),
        ('Lisandro Martinez', 'DEF', 83, False, False),
        ('Nicolas Otamendi', 'DEF', 82, False, False),
        ('Nahuel Molina', 'DEF', 80, False, False),
        ('Marcos Acuna', 'DEF', 78, False, False),
        ('Rodrigo De Paul', 'MID', 82, False, False),
        ('Enzo Fernandez', 'MID', 84, False, False),
        ('Alexis Mac Allister', 'MID', 84, False, False),
        ('Leandro Paredes', 'MID', 78, False, False),
        ('Giovani Lo Celso', 'MID', 78, False, False),
        ('Lionel Messi', 'FWD', 90, True, True),
        ('Lautaro Martinez', 'FWD', 86, True, False),
        ('Julian Alvarez', 'FWD', 84, True, False),
        ('Angel Di Maria', 'FWD', 82, False, False),
        ('Nicolas Gonzalez', 'FWD', 79, False, False),
    ],
    'ALG': [
        ("Rais M'Bolhi", 'GK', 77, True, False),
        ('Aissa Mandi', 'DEF', 77, True, False),
        ('Ramy Bensebaini', 'DEF', 78, False, False),
        ('Youcef Atal', 'DEF', 75, False, False),
        ('Mohamed Tougai', 'DEF', 73, False, False),
        ('Jaouen Hadjam', 'DEF', 73, False, False),
        ('Riyad Mahrez', 'MID', 84, True, True),
        ('Said Benrahma', 'MID', 79, True, False),
        ('Houssem Aouar', 'MID', 78, False, False),
        ('Ismael Bennacer', 'MID', 80, False, False),
        ('Adam Ounas', 'MID', 75, False, False),
        ('Islam Slimani', 'FWD', 77, True, False),
        ('Baghdad Bounedjah', 'FWD', 76, False, False),
        ('Riyad Mahrez', 'FWD', 84, False, False),
        ('Mohamed Amoura', 'FWD', 76, False, False),
        ('Yacine Brahimi', 'FWD', 75, False, False),
    ],
    'AUT': [
        ('Patrick Pentz', 'GK', 76, True, False),
        ('David Alaba', 'DEF', 84, True, False),
        ('Maximilian Wober', 'DEF', 76, False, False),
        ('Kevin Danso', 'DEF', 76, False, False),
        ('Philipp Mwene', 'DEF', 74, False, False),
        ('Stefan Posch', 'DEF', 75, False, False),
        ('Konrad Laimer', 'MID', 80, True, False),
        ('Marcel Sabitzer', 'MID', 79, True, False),
        ('Christoph Baumgartner', 'MID', 78, False, False),
        ('Florian Grillitsch', 'MID', 75, False, False),
        ('Nicolas Seiwald', 'MID', 75, False, False),
        ('Marko Arnautovic', 'FWD', 79, True, True),
        ('Michael Gregoritsch', 'FWD', 76, False, False),
        ('Marcel Sabitzer', 'FWD', 79, False, False),
        ('Patrick Wimmer', 'FWD', 73, False, False),
        ('Maximilian Entrup', 'FWD', 72, False, False),
    ],
    'JOR': [
        ('Yazeed Abulaila', 'GK', 72, True, False),
        ('Yazan Al-Arab', 'DEF', 72, True, False),
        ('Anas Bani-Yaseen', 'DEF', 72, True, False),
        ('Bara\' Marei', 'DEF', 70, False, False),
        ('Ehsan Haddad', 'DEF', 69, False, False),
        ('Salem Al-Ajalin', 'DEF', 69, False, False),
        ('Mahmoud Al-Mardi', 'MID', 72, True, False),
        ('Noor Al-Rawabdeh', 'MID', 71, False, False),
        ('Nizar Al-Rashdan', 'MID', 70, False, False),
        ('Ali Olwan', 'MID', 70, False, False),
        ('Hamza Al-Dardour', 'MID', 70, False, False),
        ('Mousa Tamari', 'FWD', 76, True, True),
        ('Yazan Al-Naimat', 'FWD', 73, False, False),
        ('Ali Olwan', 'FWD', 71, False, False),
        ('Mahmoud Mardi', 'FWD', 70, False, False),
        ('Ahmad Ersan', 'FWD', 69, False, False),
    ],
    # ── Group K ───────────────────────────────────────────────
    'POR': [
        ('Diogo Costa', 'GK', 82, True, False),
        ('Ruben Dias', 'DEF', 87, True, False),
        ('Pepe', 'DEF', 80, False, False),
        ('Joao Cancelo', 'DEF', 82, False, False),
        ('Nuno Mendes', 'DEF', 82, False, False),
        ('Antonio Silva', 'DEF', 78, False, False),
        ('Bruno Fernandes', 'MID', 87, True, False),
        ('Bernardo Silva', 'MID', 86, True, False),
        ('Vitinha', 'MID', 84, False, False),
        ('Joao Palhinha', 'MID', 80, False, False),
        ('Otavio', 'MID', 76, False, False),
        ('Cristiano Ronaldo', 'FWD', 89, True, True),
        ('Rafael Leao', 'FWD', 84, False, False),
        ('Joao Felix', 'FWD', 80, False, False),
        ('Goncalo Ramos', 'FWD', 80, False, False),
        ('Diogo Jota', 'FWD', 84, False, False),
    ],
    'COD': [
        ('Lionel Mpasi', 'GK', 73, True, False),
        ('Chancel Mbemba', 'DEF', 77, True, False),
        ('Arthur Masuaku', 'DEF', 73, False, False),
        ('Gedeon Kalulu', 'DEF', 73, False, False),
        ('Henoc Inonga', 'DEF', 71, False, False),
        ('Marcel Tisserand', 'DEF', 73, False, False),
        ('Aaron Tshibola', 'MID', 72, True, False),
        ('Samuel Moutoussamy', 'MID', 73, False, False),
        ('Charles Pickel', 'MID', 73, False, False),
        ('Edo Kayembe', 'MID', 74, False, False),
        ('Theo Bongonda', 'MID', 73, False, False),
        ('Cedric Bakambu', 'FWD', 75, True, True),
        ('Yoane Wissa', 'FWD', 76, True, False),
        ('Silas Katompa', 'FWD', 73, False, False),
        ('Meschack Elia', 'FWD', 72, False, False),
        ('Ben Malango', 'FWD', 70, False, False),
    ],
    'UZB': [
        ('Utkir Yusupov', 'GK', 73, True, False),
        ('Khojiakbar Alijonov', 'DEF', 72, True, False),
        ('Rustamjon Ashurmatov', 'DEF', 72, False, False),
        ('Farrukh Sayfiev', 'DEF', 71, False, False),
        ('Sherzod Nasrullaev', 'DEF', 70, False, False),
        ('Akram Tursunov', 'DEF', 69, False, False),
        ('Otabek Shukurov', 'MID', 72, True, False),
        ('Abbosbek Faizullaev', 'MID', 73, True, False),
        ('Jaloliddin Masharipov', 'MID', 73, False, False),
        ('Azizbek Turgunboev', 'MID', 71, False, False),
        ('Doniyor Ismoilov', 'MID', 69, False, False),
        ('Eldor Shomurodov', 'FWD', 76, True, True),
        ('Igor Sergeev', 'FWD', 73, False, False),
        ('Bobur Abdikholikov', 'FWD', 72, False, False),
        ('Khusayin Norchaev', 'FWD', 70, False, False),
        ('Jasurbek Yakhshiboev', 'FWD', 70, False, False),
    ],
    'COL': [
        ('David Ospina', 'GK', 80, True, False),
        ('Davinson Sanchez', 'DEF', 80, True, False),
        ('Yerry Mina', 'DEF', 76, False, False),
        ('Daniel Munoz', 'DEF', 78, False, False),
        ('Johan Mojica', 'DEF', 76, False, False),
        ('Carlos Cuesta', 'DEF', 75, False, False),
        ('Jefferson Lerma', 'MID', 79, True, False),
        ('James Rodriguez', 'MID', 82, True, False),
        ('Richard Rios', 'MID', 78, False, False),
        ('Mateus Uribe', 'MID', 76, False, False),
        ('Juan Quintero', 'MID', 76, False, False),
        ('Luis Diaz', 'FWD', 86, True, True),
        ('Jhon Duran', 'FWD', 78, False, False),
        ('Rafael Santos Borre', 'FWD', 76, False, False),
        ('Luis Sinisterra', 'FWD', 76, False, False),
        ('Jhon Cordoba', 'FWD', 75, False, False),
    ],
    # ── Group L ───────────────────────────────────────────────
    'ENG': [
        ('Jordan Pickford', 'GK', 82, True, False),
        ('John Stones', 'DEF', 84, False, False),
        ('Marc Guehi', 'DEF', 80, False, False),
        ('Kyle Walker', 'DEF', 82, False, False),
        ('Luke Shaw', 'DEF', 80, False, False),
        ('Trent Alexander-Arnold', 'DEF', 84, False, False),
        ('Jude Bellingham', 'MID', 87, True, False),
        ('Declan Rice', 'MID', 84, False, False),
        ('Phil Foden', 'MID', 86, True, False),
        ('Cole Palmer', 'MID', 84, False, False),
        ('Conor Gallagher', 'MID', 78, False, False),
        ('Harry Kane', 'FWD', 89, True, True),
        ('Bukayo Saka', 'FWD', 86, True, False),
        ('Anthony Gordon', 'FWD', 80, False, False),
        ('Ollie Watkins', 'FWD', 80, False, False),
        ('Eberechi Eze', 'FWD', 79, False, False),
    ],
    'CRO': [
        ('Dominik Livakovic', 'GK', 82, True, False),
        ('Josko Gvardiol', 'DEF', 82, True, False),
        ('Josip Sutalo', 'DEF', 76, False, False),
        ('Borna Sosa', 'DEF', 75, False, False),
        ('Josip Stanisic', 'DEF', 75, False, False),
        ('Martin Erlic', 'DEF', 73, False, False),
        ('Luka Modric', 'MID', 86, True, True),
        ('Mateo Kovacic', 'MID', 82, True, False),
        ('Marcelo Brozovic', 'MID', 79, False, False),
        ('Mario Pasalic', 'MID', 76, False, False),
        ('Nikola Vlasic', 'MID', 75, False, False),
        ('Andrej Kramaric', 'FWD', 80, True, False),
        ('Bruno Petkovic', 'FWD', 76, False, False),
        ('Mislav Orsic', 'FWD', 75, False, False),
        ('Ante Budimir', 'FWD', 73, False, False),
        ('Marko Pjaca', 'FWD', 72, False, False),
    ],
    'GHA': [
        ('Lawrence Ati-Zigi', 'GK', 75, True, False),
        ('Mohammed Salisu', 'DEF', 77, True, False),
        ('Daniel Amartey', 'DEF', 75, False, False),
        ('Alidu Seidu', 'DEF', 73, False, False),
        ('Gideon Mensah', 'DEF', 73, False, False),
        ('Tariq Lamptey', 'DEF', 75, False, False),
        ('Mohammed Kudus', 'MID', 80, True, True),
        ('Thomas Partey', 'MID', 80, True, False),
        ('Salis Abdul Samed', 'MID', 75, False, False),
        ('Andre Ayew', 'MID', 76, False, False),
        ('Edmund Addo', 'MID', 73, False, False),
        ('Inaki Williams', 'FWD', 79, True, False),
        ('Antoine Semenyo', 'FWD', 76, False, False),
        ('Jordan Ayew', 'FWD', 75, False, False),
        ('Ernest Nuamah', 'FWD', 74, False, False),
        ('Felix Afena-Gyan', 'FWD', 73, False, False),
    ],
    'PAN': [
        ('Orlando Mosquera', 'GK', 73, True, False),
        ('Cesar Blackman', 'DEF', 73, True, False),
        ('Andres Andrade', 'DEF', 72, False, False),
        ('Michael Amir Murillo', 'DEF', 73, False, False),
        ('Eric Davis', 'DEF', 71, False, False),
        ('Jose Cordoba', 'DEF', 71, False, False),
        ('Adalberto Carrasquilla', 'MID', 75, True, True),
        ('Yoel Barcenas', 'MID', 74, True, False),
        ('Anibal Godoy', 'MID', 73, False, False),
        ('Cristian Martinez', 'MID', 72, False, False),
        ('Ivan Anderson', 'MID', 70, False, False),
        ('Cecilio Waterman', 'FWD', 73, True, False),
        ('Ismael Diaz', 'FWD', 73, False, False),
        ('Jose Fajardo', 'FWD', 72, False, False),
        ('Edgar Barcenas', 'FWD', 72, False, False),
        ('Eduardo Guerrero', 'FWD', 71, False, False),
    ],
}


# ──────────────────────────────────────────────────────────────
# 추가 선수 (+3/팀: 1 DEF + 1 MID + 1 FWD)
# 실제 국가대표 호출 명단 기준. 약체팀은 plausible 이름 일부 포함.
# ──────────────────────────────────────────────────────────────

EXTRA_PLAYERS = {
    # Group A
    'MEX': [('Israel Reyes', 'DEF', 75, False, False),
            ('Carlos Rodriguez', 'MID', 75, False, False),
            ('Diego Lainez', 'FWD', 75, False, False)],
    'RSA': [('Innocent Maela', 'DEF', 70, False, False),
            ('Goodman Mosele', 'MID', 70, False, False),
            ('Bongokuhle Hlongwane', 'FWD', 71, False, False)],
    'KOR': [('박진섭', 'DEF', 73, False, False),
            ('박용우', 'MID', 71, False, False),
            ('정상빈', 'FWD', 70, False, False)],
    'CZE': [('Jaroslav Zeleny', 'DEF', 71, False, False),
            ('Antonin Barak', 'MID', 76, False, False),
            ('Jan Kuchta', 'FWD', 73, False, False)],
    # Group B
    'CAN': [('Moise Bombito', 'DEF', 73, False, False),
            ('Liam Fraser', 'MID', 71, False, False),
            ('Ike Ugbo', 'FWD', 72, False, False)],
    'BIH': [('Adnan Kovacevic', 'DEF', 71, False, False),
            ('Haris Hajradinovic', 'MID', 72, False, False),
            ('Sasa Zigic', 'FWD', 71, False, False)],
    'QAT': [('Homam Ahmed', 'DEF', 71, False, False),
            ('Hamam Al-Amin', 'MID', 70, False, False),
            ('Ahmed Alaaeldin', 'FWD', 71, False, False)],
    'SUI': [('Eray Comert', 'DEF', 74, False, False),
            ('Fabian Rieder', 'MID', 75, False, False),
            ('Noah Okafor', 'FWD', 76, False, False)],
    # Group C
    'BRA': [('Lucas Beraldo', 'DEF', 80, False, False),
            ('Andreas Pereira', 'MID', 78, False, False),
            ('Pedro', 'FWD', 80, False, False)],
    'MAR': [('Jawad El Yamiq', 'DEF', 75, False, False),
            ('Ismael Saibari', 'MID', 75, False, False),
            ('Brahim Diaz', 'FWD', 79, False, False)],
    'HAI': [('Jephte Aguilar', 'DEF', 68, False, False),
            ('Wesley Lautoa', 'MID', 68, False, False),
            ('Ronaldo Damus', 'FWD', 70, False, False)],
    'SCO': [('Aaron Hickey', 'DEF', 76, False, False),
            ('Ryan Christie', 'MID', 75, False, False),
            ('James Forrest', 'FWD', 73, False, False)],
    # Group D
    'USA': [('Cameron Carter-Vickers', 'DEF', 76, False, False),
            ('Johnny Cardoso', 'MID', 76, False, False),
            ('Haji Wright', 'FWD', 75, False, False)],
    'PAR': [('Fabian Balbuena', 'DEF', 75, False, False),
            ('Hernesto Caballero', 'MID', 70, False, False),
            ('Roque Santa Cruz', 'FWD', 73, False, False)],
    'AUS': [('Joel King', 'DEF', 71, False, False),
            ('Jackson Irvine', 'MID', 75, False, False),
            ('Bruno Fornaroli', 'FWD', 72, False, False)],
    'TUR': [('Zeki Celik', 'DEF', 75, False, False),
            ('Orkun Kokcu', 'MID', 76, False, False),
            ('Yunus Akgun', 'FWD', 75, False, False)],
    # Group E
    'GER': [('Benjamin Henrichs', 'DEF', 76, False, False),
            ('Leon Goretzka', 'MID', 80, False, False),
            ('Karim Adeyemi', 'FWD', 80, False, False)],
    'CUW': [('Diego Diaz', 'DEF', 70, False, False),
            ('Roly Bonevacia', 'MID', 70, False, False),
            ('Bastian Cuypers', 'FWD', 70, False, False)],
    'CIV': [('Willy Boly', 'DEF', 76, False, False),
            ('Sekou Sangare', 'MID', 73, False, False),
            ('Christian Kouame', 'FWD', 75, False, False)],
    'ECU': [('Jackson Porozo', 'DEF', 73, False, False),
            ('Patrickson Delgado', 'MID', 72, False, False),
            ('Ayrton Preciado', 'FWD', 73, False, False)],
    # Group F
    'NED': [('Stefan de Vrij', 'DEF', 80, False, False),
            ('Marten de Roon', 'MID', 76, False, False),
            ('Steven Bergwijn', 'FWD', 78, False, False)],
    'JPN': [('Shogo Taniguchi', 'DEF', 76, False, False),
            ('Hidemasa Morita', 'MID', 76, False, False),
            ('Shuto Machino', 'FWD', 73, False, False)],
    'SWE': [('Jonas Knudsen', 'DEF', 71, False, False),
            ('Jens-Lys Cajuste', 'MID', 75, False, False),
            ('Anthony Elanga', 'FWD', 76, False, False)],
    'TUN': [('Mortadha Ben Ouanes', 'DEF', 71, False, False),
            ('Anis Ben Slimane', 'MID', 73, False, False),
            ('Naim Sliti', 'FWD', 73, False, False)],
    # Group G
    'BEL': [('Jan Vertonghen', 'DEF', 78, False, False),
            ('Hans Vanaken', 'MID', 75, False, False),
            ('Michy Batshuayi', 'FWD', 76, False, False)],
    'EGY': [('Mahmoud Hassan', 'DEF', 73, False, False),
            ('Tarek Hamed', 'MID', 73, False, False),
            ('Ahmed Sayed Zizo', 'FWD', 73, False, False)],
    'IRN': [('Morteza Pouraliganji', 'DEF', 73, False, False),
            ('Saman Ghoddos', 'MID', 74, False, False),
            ('Karim Ansarifard', 'FWD', 73, False, False)],
    'NZL': [('Michael Boxall', 'DEF', 71, False, False),
            ('Joe Bell', 'MID', 71, False, False),
            ('Kosta Barbarouses', 'FWD', 71, False, False)],
    # Group H
    'ESP': [('Inigo Martinez', 'DEF', 80, False, False),
            ('Mikel Merino', 'MID', 79, False, False),
            ('Joselu', 'FWD', 75, False, False)],
    'CPV': [('Sidnei Tavares', 'DEF', 71, False, False),
            ('Jamiro Monteiro', 'MID', 73, False, False),
            ('Garry Rodrigues', 'FWD', 72, False, False)],
    'KSA': [('Ali Al-Bulaihi', 'DEF', 74, False, False),
            ('Nasser Al-Dawsari', 'MID', 73, False, False),
            ('Firas Al-Buraikan', 'FWD', 73, False, False)],
    'URU': [('Jose Maria Gimenez', 'DEF', 82, False, False),
            ('Manuel Ugarte', 'MID', 80, False, False),
            ('Luis Suarez', 'FWD', 80, False, False)],
    # Group I
    'FRA': [('Ibrahima Konate', 'DEF', 81, False, False),
            ('Eduardo Camavinga', 'MID', 82, False, False),
            ('Marcus Thuram', 'FWD', 82, False, False)],
    'SEN': [('Pape Abou Cisse', 'DEF', 73, False, False),
            ('Pathe Ciss', 'MID', 73, False, False),
            ('Boulaye Dia', 'FWD', 78, False, False)],
    'IRQ': [('Manaf Younis', 'DEF', 70, False, False),
            ('Amir Al-Ammari', 'MID', 72, False, False),
            ('Ali Al-Hamadi', 'FWD', 72, False, False)],
    'NOR': [('Kristoffer Ajer', 'DEF', 76, False, False),
            ('Fredrik Aursnes', 'MID', 75, False, False),
            ('Antonio Nusa', 'FWD', 76, False, False)],
    # Group J
    'ARG': [('Lisandro Martinez', 'DEF', 83, False, False),
            ('Alexis Mac Allister', 'MID', 84, False, False),
            ('Angel Di Maria', 'FWD', 82, False, False)],
    'ALG': [('Ramy Bensebaini', 'DEF', 78, False, False),
            ('Ismael Bennacer', 'MID', 80, False, False),
            ('Mohamed Amoura', 'FWD', 76, False, False)],
    'AUT': [('Maximilian Wober', 'DEF', 76, False, False),
            ('Christoph Baumgartner', 'MID', 78, False, False),
            ('Michael Gregoritsch', 'FWD', 76, False, False)],
    'JOR': [('Salem Al-Ajalin', 'DEF', 70, False, False),
            ('Nizar Al-Rashdan', 'MID', 71, False, False),
            ('Yazan Al-Naimat', 'FWD', 73, False, False)],
    # Group K
    'POR': [('Antonio Silva', 'DEF', 78, False, False),
            ('Vitinha', 'MID', 84, False, False),
            ('Diogo Jota', 'FWD', 84, False, False)],
    'COD': [('Marcel Tisserand', 'DEF', 73, False, False),
            ('Edo Kayembe', 'MID', 74, False, False),
            ('Silas Katompa', 'FWD', 73, False, False)],
    'UZB': [('Akmal Mozgovoy', 'DEF', 70, False, False),
            ('Jaloliddin Masharipov', 'MID', 73, False, False),
            ('Bobur Abdikholikov', 'FWD', 72, False, False)],
    'COL': [('Yerry Mina', 'DEF', 76, False, False),
            ('Mateus Uribe', 'MID', 76, False, False),
            ('Rafael Santos Borre', 'FWD', 76, False, False)],
    # Group L
    'ENG': [('Lewis Dunk', 'DEF', 80, False, False),
            ('Declan Rice', 'MID', 84, False, False),
            ('Cole Palmer', 'FWD', 84, False, False)],
    'CRO': [('Domagoj Vida', 'DEF', 76, False, False),
            ('Marcelo Brozovic', 'MID', 79, False, False),
            ('Bruno Petkovic', 'FWD', 76, False, False)],
    'GHA': [('Daniel Amartey', 'DEF', 75, False, False),
            ('Salis Abdul Samed', 'MID', 75, False, False),
            ('Jordan Ayew', 'FWD', 75, False, False)],
    'PAN': [('Andres Andrade', 'DEF', 72, False, False),
            ('Anibal Godoy', 'MID', 73, False, False),
            ('Jose Fajardo', 'FWD', 72, False, False)],
}


# 기존 SQUADS에 EXTRA_PLAYERS 병합 — 중복 이름은 건너뜀
# (EXTRA_PLAYERS의 일부 이름이 이미 SQUADS에 있을 경우 안전)
for _code, _extras in EXTRA_PLAYERS.items():
    if _code in SQUADS:
        _existing = {p[0] for p in SQUADS[_code]}
        for _p in _extras:
            if _p[0] not in _existing:
                SQUADS[_code].append(_p)
                _existing.add(_p[0])


def main():
    # 검증 — 1 GK + 6 DEF + 6 MID + 6 FWD = 19
    target = {'GK': 1, 'DEF': 6, 'MID': 6, 'FWD': 6}
    bad = []
    for code, squad in SQUADS.items():
        counts = {'GK': 0, 'DEF': 0, 'MID': 0, 'FWD': 0}
        for p in squad:
            counts[p[1]] += 1
        if counts != target:
            bad.append((code, counts))
    if bad:
        print('WARN: role distribution off:')
        for code, c in bad:
            print(f'  {code}: {c}')

    # JSON 형식으로 변환
    squads = {}
    for code, plist in SQUADS.items():
        squads[code] = [
            {'name': name, 'role': role, 'rating': rating,
             'is_star': bool(is_star), 'pk_taker': bool(pk_taker)}
            for (name, role, rating, is_star, pk_taker) in plist
        ]

    out_path = Path(__file__).parent / 'squads.json'
    data = {
        '_meta': {
            'description': '48 teams × 16 real national-team players. KOR in 한글.',
            'role_distribution': '1 GK / 5 DEF / 5 MID / 5 FWD = 16',
            'fields': {
                'name': '선수명 (real)',
                'role': 'GK / DEF / MID / FWD',
                'rating': '60~91 (스타 75~91)',
                'is_star': '스타 여부 (5/팀)',
                'pk_taker': 'PK 전담 키커',
            },
        },
        'squads': squads,
    }
    out_path.write_text(json.dumps(data, ensure_ascii=False, indent=2),
                         encoding='utf-8')
    n_total = sum(len(s) for s in squads.values())
    print(f'wrote {out_path}')
    print(f'  teams: {len(squads)}, players: {n_total}')


if __name__ == '__main__':
    main()
